### ISSUE TITLE
Раскладка не подхватывается

### ISSUE THREAD

**Issue by vovanmozg** [moigagoo/universal-layout-linux#1]
Заменил файлы, как описано в README, ребутнулся, но изменения не подхватились.

**Comment by moigagoo** [comment]
Новые раскладки не показываются в списке доступных в настройках?

**Comment by vovanmozg** [comment]
Смотрю в Settings/Keyboard/Input Sources, там без изменений

**Comment by moigagoo** [comment]
А у вас какое окружение рабочего стола? Я тестил на КДЕ только.

**Comment by vovanmozg** [comment]
Gnome. Попробую разобраться, если что-то получится, напишу

**Comment by moigagoo** [comment]
@vovanmozg не удалось ли починить в Гноме?

**Comment by moigagoo** [comment]
Я сегодня переехал на Гном, и у меня раскладка подсосалась. Сначала я забыл заменить evdev.xml, потом надо было было перезайти в систему, но в конце концов всё работает.

**Comment by vovanmozg** [comment]
> @vovanmozg не удалось ли починить в Гноме?

Я ещё раз попробовал разобраться, но пока безрезультатно. Как только что-то получится, сразу напишу

**Comment by vovanmozg** [comment]
Я хочу попробовать воспроизвести по шагам изменения, но столкнулся с тем, что слишком много отличий между файлами в моей системе и файлами из репо.

```
# diff evdev.xml ../evdev.xml | wc -l
683
# diff ru ../ru | wc -l
98
# diff us ../us | wc -l
215
```
Моя система
```
# uname -a
Linux vpkatana 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Сохранились ли у вас оригинальные файлы, чтобы можно было посмотреть дифф и воспрозвести изменения по шагам?

**Comment by moigagoo** [comment]
Сохранились, пришлю в течение дня.

**Comment by moigagoo** [comment]
@vovanmozg https://gist.github.com/moigagoo/642eb03f8977aa82b78a1dd0f54c505a

**Comment by moigagoo** [comment]
Если ничего не поможет, попробуйте ещё дописать в /usr/share/X11/xkb/rules/evdev.lst новые раскладки: https://gist.github.com/moigagoo/33d22fb3006c47b89e62c45ce1304324

**Comment by vovanmozg** [comment]
Всё получилось. Пришлось немного разобраться, как устроены раскладки Linux/X11. Затем сравнил файлы из репозитория и из своей системы и аккуратно перенёс нужные изменения, на этот раз понимая, что делаю :laughing:
https://github.com/vovanmozg/universal-layout-linux/commit/8d0732801c4d2346463aba184ec57ae6d2446e83

После этого ребутнулся и установил нужные раскладки.

Не понятно, что я делал не так до этого

**Comment by vovanmozg** [comment]
Спасибо за помощь :)
